# Generated by Django 5.2.6 on 2025-09-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrun',
            name='current_num',
            field=models.IntegerField(default=1),
        ),
    ]
